### ISSUE TITLE
US1 - render fetched cards

### ISSUE THREAD

**Issue by WE-Kaito** [WE-Kaito/digimon-tcg-simulator#1]
## Value proposition

As a user
I want to see the card library

## Description

![Image](https://user-images.githubusercontent.com/98795399/255400709-b1eca4f0-1a8d-4855-b2d6-d8581bd1b5e6.png)

## Acceptance criteria

- [x]  I can see all existing cards in a list ordered alphbetically

## Tasks

- [x] card model
- [x] card controller with GET endpoint for /api/cards
- [x]  card service with webclient fetch: `https://digimoncard.io/api-public/search.php?series=Digimon%20Card%20Game`
---
- [x] Deckbuilder page with basic grid layout
- [x] get request
- [x] card Type
- [x] map the fetched data and return Card component.
- [x] styled image
