### ISSUE TITLE
US10 - Lobby Invite

### ISSUE THREAD

**Issue by WE-Kaito** [WE-Kaito/digimon-tcg-simulator#10]
## Value proposition

As a user
I want to click on my friends name
to invite him to a game

## Description

![Image](https://user-images.githubusercontent.com/98795399/255432282-769241a0-e38c-4270-98ee-5633514038bd.png)

## Acceptance criteria

- [x]  ```Invite``` Button on the nameplate of each user
- [x] On pressing ```Invite``` a moodle loads waiting for a response
- [x] I can abort the invitation
- [x] The invited player can accept_(next US)_ or deny the invitation as long as it is not aborted.
- [x] The 2 players are not shown in the lobby list as long as they have a pending invitation

## Tasks

- [ ]
