### ISSUE TITLE
US12 - Cards in Game

### ISSUE THREAD

**Issue by WE-Kaito** [WE-Kaito/digimon-tcg-simulator#12]
## Value proposition

As a user
I want to have my deck in the game
for the basic setup

## Description

![Image](https://user-images.githubusercontent.com/98795399/255432497-dd46b677-aa6a-4df0-875b-71be94ded8ce.png)

![Image](https://github.com/WE-Kaito/digimon-tcg-simulator/assets/98795399/d607cdce-2999-4ea3-8635-9dd567e5a051)

## Acceptance criteria

- [x]  Cards are shuffled and distributed
- [x]  Opponents hand is hidden
- [x]  Security stacks are hidden
- [x]  Info link to rulings at top: `https://world.digimoncard.com/rule/pdf/general_rules.pdf`
- [x]  The details of a card are displayed same as in the deckbuilder by clicking/hovering.

## Tasks

- [ ]
