### ISSUE TITLE
US13 - Drag Cards to other Fields

### ISSUE THREAD

**Issue by WE-Kaito** [WE-Kaito/digimon-tcg-simulator#13]
## Value proposition

As a user
I want to drag the cards around
so the game is playable.

## Description

![Image](https://user-images.githubusercontent.com/98795399/255432551-beb51e69-5f87-4701-b2c2-0b7e97063e04.png)

## Acceptance criteria

- [x]  Cards are draggable to other Fields
- [x] I can decide wheter I put the card at the top or bottom of deck and security
- [X] Moving cards is correctly displayed for the opponent 
- [x] by clicking the deck I draw a card
- [x] by clicking the egg-deck I send the top card to the breeding zone
- [X] by pressing a button I can open the trash 

## Tasks

- [ ]
