### ISSUE TITLE
US15  - reveal Cards

### ISSUE THREAD

**Issue by WE-Kaito** [WE-Kaito/digimon-tcg-simulator#15]
## Value proposition

As a user
I want to show cards from my hand or from my deck to my enemy

## Description

![Image](https://user-images.githubusercontent.com/98795399/255432870-3fd885b1-3c97-44c6-a744-bfcdc307902d.png)

## Acceptance criteria

- [X]  Cards from Hand, Deck and Security can be revealed
- [X]  by pressing the reveal button, a card is shown in the middle of the screen
- [X] I can not reveal cards while the opponent is revealing

## Tasks

- [ ]
