### ISSUE TITLE
US2 - filter cards

### ISSUE THREAD

**Issue by WE-Kaito** [WE-Kaito/digimon-tcg-simulator#2]
## Value proposition

As a user
I want to have a search form
to find specific cards

## Description

![Image](https://user-images.githubusercontent.com/98795399/255431474-6164f0f1-3680-4daf-a9be-0d7aa39613c7.png)

## Acceptance criteria

- [x]  a search field with inputs and a button is displayed
- [x]  i can change all the search criteria
- [x]  when pressing the button the card list is filtered

## Tasks

- [ ] Get Request with Requestbody of form data (refactor first request?)
- [ ] filter function in cardservice
- [ ] test
----
- [ ] add form
- [ ] handlesubmit
