### ISSUE TITLE
US5 - Routing (Menu, Profile Page, Edit Deck)

### ISSUE THREAD

**Issue by WE-Kaito** [WE-Kaito/digimon-tcg-simulator#5]
## Value proposition

As a user
I want to be able to access  my profile
to see and update my Decks

## Description

![Image](https://user-images.githubusercontent.com/98795399/255431752-f2feddaf-e838-46e1-9711-0216587eea56.png)

## Acceptance criteria

- [x] When starting the App I get to the main Menu
- [x] There is a navigation to to the Deck Builder and the Profile Page
- [x] The saved decks are displayed on the Profile page
- [x] The Decks are colored by its most occuring color
- [x] by clicking on a Deck I can access an edit Page to update or delete it  
- [x] there is a "back" button on every page

## Tasks

- [ ]
