### ISSUE TITLE
US7 - update Profile & models

### ISSUE THREAD

**Issue by WE-Kaito** [WE-Kaito/digimon-tcg-simulator#7]
## Value proposition

As a user
I want to save and access decks in my account

## Description

![Image](https://user-images.githubusercontent.com/98795399/255432102-88c27648-a72b-40ab-b65d-b75e9ba26b69.png)

## Acceptance criteria

- [x]  You can set your avatar on the profile page.
- [x] You can also choose your active deck

## Tasks

- [x] String activeDeckId on user
- [x] String avatarName on user
